--[[

MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXOxk0KKKKK0OOOOOOOKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMMWWWNKxl;...''''''........;d0XNWWWWMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNK0Okxoc,......................':cooxkkOKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNKxc'......................................,l0NWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOl'...........................................oXWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMWNOl'..............................',;,..........:ONWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWNXKkl,............................';cdkO0Odlccc:;,',xNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNkc;,..............................:k0KK0OO00000OOOOkxkKNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNO:................';:llollc;,.....:kKK0kkO00OOkkOO00K0OkOXWMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWXd'.............':ok0KKKKKK00Okdc,,o0K000KK0OO00KKKKKKKK0kkKWMWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNk,...........'cx0KKKKKKKKKKKKKK0OddOKKKKKKKKKKK00KKKKKKK0kkKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWXd'........'ck0KKKKKKK00000KKKKKKOxk0KKKKKK0kxkkkkOKKKKKK0kkXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNkc'....,lk0KKKKKKKOdc;,;lxO0KKK0OxxkkOOO0kxOOkkkxk0KKKKKOxONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNx:lxkOK0O0KKKK0d;...';cok0KKKKK0OOOkxxkkxkocldddx0KKKKKkdONMWWMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMW0dOKKKK0xk0KKOl'..'cxkxxkO0KKKKKKKKK0kxdxkl:clxdlxkOOOkxxxONWWMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0xOKKKK0xokOx:...,oxxo:,cx0KKK0OO00KKK0O00Oxox0xlokkkkk0KOxONWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKololllllool,..':lxkOd:;lOKKK0xoxO0KKKKKKK0kxO0dlxKKKKKKKKOxONWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOc,'',',lkkocokdlx0kddk0KKKK0dlxO0KKKKKK0kdkOxodOKKKKKKKK0Ok0NWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOolol:oO0xxOKOxO000KKKKKKKKkllox0KKKKKK0kxooxO0KKKKKKKKK0Ok0NWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWKkxocoOOdoOK0000KKKKKKKKKK0xlclk0KKKKKKOdodk0KKKKKKKKKKK0kk0NWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWN0xkxdOOddkOkxxddoddxxkO0KK0dlcoOKKKKKOdooodkO0OOkxxdddoolcldk0NWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKkkxdO0kkko,.........':oO0KOkdld0KKK0xlllccclcc:;;;,,,,,,,,;;:dKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOdodO0Odc,..........;lx0KKKKOolk0K0d:;;;,,,,;;;;;;;;;;;;;;;;;:dKWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXkdol;,..........;ok0KKKKKKKKkodOOo;',,,;;;;;;;;;;;;;;;;;;;;;;:xXWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOo,.........'cdOKKKKKKKKKKK0xooc,,;;,;;;;;;;;;;;;;;;;;;;::::;:xKNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNk;.....',:lxOO0KKKKKKKKKK0Oxl;,',,;;;;;;;;;;;;;;;;;;;;::::::;:loxO0XNWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWOc,:oxkkxxxkO0KKKK0Okxoolc:;,,;;;;;;;;;;;;;;;;;;;;;;;;::::cc:::::cloxkKXNWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWW0xk0KK0OOO0K0Okdlc:;;,,,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;::::::::::::;;;;:coxOKNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWKOO0KK0Okdoc:;,,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:::::::::::;;;;;,,,,;:lxk0XNWWMMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMMMWWWNKxddoc:;;,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:::::::;;;;;;;;;;;;;,,,;:cox0XNWWWWWWMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWMWWNKkoc;;,,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,,,,,;:coxOXWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWN0xl:;,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,;;;;cdkKNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMWWWNKko:,,,;;;,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,;cokKNWMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMMMMMWWNNXKKKK00000000K00000KKKXXXNNNWWWWMMMMMMMWWN0dc;,;;;;,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,;cdOXNWWMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWNXK0000OO00000KKKKKKKKKKKKKK000000O00000KXXWWWWN0d:;;,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,;;;;;:lxKNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNX0OOOO0KXXNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXKK0OOOO0K0x:,,;;;,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:::::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;cxKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNKOOO0KXNNNNNNWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXKKOo;,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;::::::::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,;;;;,;cxKNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWMWNKOkO0KXNNNNNNNNWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNKo,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;::::::::::;;;;;;;;;;;;;;;;;;;;:::::::;;;;;;;;;;;;;;;;;;;;;;;,,,,;;;;;,,;cxKNWWMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNKOO0KNNNNWWNWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN0l,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;::::cc::::::;;;;;;;;;;;;;;;;;;:::::::::;;;;;;;;;;;;;;;;;;;;;;,,,,,;;,,;;;;ckXWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWXOk0XNNNNNNNWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNOl;,;;;,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:::::cc:::::;;;;;;;;;;;;;;;;;;::::::::::;;;;;;;;;;;;;;;;;;;;;,,,,,,;;;;;;,;o0NWWWMMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWN0kOXNNNNWWWNWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXx:;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;::::ccc::::;;;;;;;;;;;;;;;;;;;::::::::::;;;;;;;;;;;;;;;;;;;;;;;,,,,,;;;;,,,cxKXKKKKK0000KKKKKKXXXXNNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOk0XNNNNNWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN0o;;;;;;;;;;;;;;;,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:::::ccc::::;;;;;;;;;;;;;;;;;;:::::::::;;;;;;;;;;;;;;;;;;;;;;;;,,,'',;;;;;,:x0000KKKKKKKKKK000K0000000KXNWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKkOXNNNNNWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNKx:,,;;;;;;;;;;;;;;;;;;;;;;,,,,,;;;;;;;;;;;;;;;;;::::cccc:::;;;;;;;;;;;;;;;;;;;:::::::::;;;;;;;;;;;;;;;;;;;;;;;,,,,,',,;;,,:ONNNNNNNNNNNNNNNNNNNNNNXKK0OOO0NWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWXkOXNNNNNNWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXkc,;;;;;;;;;;;;;;;;;;;;;;;;;,,'',,;;;;;;;;;;;;;;;::::ccccc:::;;;;;;;;;;;;;;;;;;;::::::::::;;;;;;;;;;;;;;;;;;;;;;;,,,,,,,;,,lKNXNNNNNNNNNNNNNNWWWWWNNNNNNX0OkOKNMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOkKNNNNWWNNWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXKkc,,;;;;;;;;;;;;;;;::::;;;;;;;;,,''',;;;;;;;;;;;;;::::cccccc:::;;;;;;;;;;;;;;;;;;::::::::::;;;;;;;;;;;;;;;;;;;;;;;;;;;,,,;,;xXNNNNNNNNNNWWWWWWWWWWWWWWWNNNNNX0OOKNWMWMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0k0NNNNNWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXKkl,,,;;;;;;;;;;;;;:::::::;;;;;;;;,,'''',,;;;;;;;;;;;::::ccccc:::;;;;;;;;;;;;;;;;;;:::::c:::::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,;kXNNNNNNNNNWWWWWWWWWWWWWWWWWWWWWNNXKOO0NWMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOOXNNNWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXKOxl,,;;;;;;;;;;;;;;:::::::::;;;;;;;;;;,'..',,;;;;;;;;;;:::ccccc::::;;;;;;;,,,,;;;;;;;:::::::::::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,;dXNNNNNNNNNNNNNWWWWWWWWWWWWWWWWWWWWNXKOk0NMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKk0NNNNWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXK0kxc;,;;;;;;;;;;;;;;;::::::::::;;;;;;;;;;,''.',,;;;;;;;;;::::ccccc:::;;;;;;;;,,,,;;;;;;;::::::::::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,l0NNNNNNNNNNNNNNNNNNNNNWWWWWWWWWWWWWWNN0kOXWMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOOKNNNNWWWWNNNNNNNNXXXXNNNNNNNNNNNNNNNNNXNNNNNXXXXKKK0Okkxdc;,,;;;;;;;;;;,;;;;::::::::::;;;;;;;;;;,,,'''',;;,;;;;;::::ccccc::::;;;;;;;,,,,,;;;;;;;::::cc::::;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,:kXNNNNNNNNNNNNNNNNNNNNNNNWWWWWWWWWWWNWWXOkKNMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXkOXNNNNWWWNNNNNNX0OOOOKXNNNNNNNNNNNNNNNNNNXK0Okkkxxxddddol:;,,,,;;;;;;;;,,,;;;::::::::::;;;;;;;;;;;,,,'''',;;;;;;;;:::ccccc:::::;;;;;;;,'',;;;;;;;::::cc::::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,oKNXNNNNNNNNNNNNNNNNNNNNNNNNWWWWWWWWWWWNN0k0NWMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKkONNNNNNNNNNXK0OkO0KXNNWWWWWWWWWNNNNNNNNXKOkkkOOOOkxxxdl:;,,,,,;;;;;;;;;,,,;;;::::::::::;;;;;;;;;;;;;;,'...,;;;;;;;;:::ccccc::::;;;;;;;,'',;;;;;;;::::cc:::::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,:xXNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWWWWWWWNNN0kKWMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKxONNNNNNNXK0kkOKXNWWWWWWWWWWWWWWWNNNNNNNXKKXXXK0Okkkxoc;,,,,,,,;;;;;;;;;;,,,;;::::::::::;;;;;;;;;;;;;;,,'..',;;;;;;;:::cccccc:::;;;;;;;,,'',;;;;;;:::::cc:::::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,ckKXXNNNNNNNNNNNNNNNNNNNNNNNNNNWWWWWWWWNNXOOXWMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKxOXNNNNX0OkO0XNWWWWWWWWWWWWWWWWWWNNNNNNNNNXKK0Okxxxoc;,,;,,;;;,;;;;;;;;;;,,,;;::::::::::;;;;;;;;;;;;;;;,,'..',;;;;;;:::cccccc:::;;;;;;;;,'',,;;;;;:::::ccc::::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,:oxO0KXNNNNNNNNNNNNNNNNNNNNNNNNNWWWWWWWWWKk0NMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXkOXNNN0xdOKXNWWWWWWWWWWWWWWWWWWWWNNNNNNNXKOkkkkxdoc;,,,;;,;;;;;;;;;;;;;;;,,,;;::::::::::;;;;;;;;;;;;;;;,,'...',;;;;;;:::ccccc::::;;;;;;;,'.',;;;;;;:::::ccc:::;;;;;;;;;;;;;;;;;;;;;;;,,;;;;;,;coxxxkO0KXXNNNNNNNNNNNNNNNNNNNNWWWWWWWWWNOkKMMWMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNOOKNKkox0XNNNWWWWWWWWWWWWWWWWWWWWNNNNXK0Okkkkxdl:;,,;;;;;;;;;;;;;;;;;;;;,,,;;::::::::::;;;;;;;;;;;;;;;;;,''...',;;;;;::::cccc::::;;;;;;;,'.',;;;;;;;:::::cc:::;;;;;;;;;;;;;;;;;;;:::;;;,,,;;;,;cdkxxxxkO0XNNNNNNNNNNNNNNNNNNNNNNWWWNNNNKk0WMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKO00xox0XNNNWWWWWWWWWWWWWWWWNNNNNXXK0Okkxxxdl:;,,;;;;;;;;;;;;;;;;;;;;;;;,,,;::::::::::;;;;;;;;;;;;;;;;;;,''....',;;;;:::::::::::;;;;;;;;,'..',;;;;;;::::ccc:::::;;;;;;;;;;;;;;;;:::::::;,,,;;;,;cddodxkkOKXNNNNWWWWWWWWWNNNNXKXNNNNWNNNXkONMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOxoox0XNNNNWWWWWWWWWNNNNNNNNNXK0OOkkkxxol:;,,,;;;;;;;;;;;;;;;;;;;;;;;;,,,;::::::::::;;;;;;;;;;;;;;;;;;;,,'.....',;;;;;:::::::;;;;;;;;;;;,'..,;;;;;;::::cc::::::;;;;;;;;;;;;;;;;;:::::::;;,'',,,,:cldkO0XXNNNNWWWWWWWWWWWNNNX0OOKNNNNNNXxxKWWMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0olx0XNNNNNNNNNNNNNNNNNXXXK00Okkkkxdoc:;,,,;;;;;;;;;;;;;;;;;;;;;;;;;;,,,;;::::::::::;;;;;;;;;;;;;;;;;;;,,'......,;;;;;;;;;;;;;;;;;;;;;;;,'..',;;;;;::::cccc::::;;;;;;;;;;;;;;;;;;:::::::;;,,,',,,,cdk0XNNNNNWWWWWWWWWWWWWWNNNKOkOKNNNNKddKMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOddOKNNNNNNNNNNNNNXXKK00Okkkkxxxdl:;,,,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;,,,;:::::::::::;;;;;;;;;;;;;;;;;;;;,,'......',;;;;;;;;;;;;;;;;;;;;;;,'...,;;;;;;::::cccc::::;;;;;;;;;;;;;;;;;:::::::::;;;,,,,,,:dOKXNNNNWWWWWWWWWWWWWWWWNNXKOxOXNXOdxXMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMWXxdkKXNNNNXXXXXKK00OOkkkxxxxxdoc:;,,,,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,,;;::::::::::;;;;;;;;;;;;;;;;;;;;;,,'.......',;;;;;;;;;;;;;;;;;;;;;,'...',;;;;;;::::ccccc:::;;;;;;;;;;;;;;,;;:::::::::;;;;;,,,,;lkKXNNNNWWWWWWWWWWWWWWWNNNNX0kkOOxoOWMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0ddk0KKK00OOOOkkkkkkkkxxdolc:;,,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,,;;::::::::::;;;;;;;;;;;;;;;;;;;;;;,''.......',,;;;;;;;,;;;;;;;;;;;,''....',;;;;;;::::ccccc:::;;;;;;;;;;;;;;;;;::::::::;;;;;;;;,,;:dOXNNNNNNWWWWWWWWWWWWNNNNNNKkooodKWMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOddkkkkkkkkkkkkkxxxxdoc:;,,,,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,,;:::::::::::;;;;;;;;;;;;;;;;;;;;;;;,'.........',;;;;;;,,;;;;;;;;;;;,''....',,;;;;;;::::cccc::::;;;;;;;;;;;;;;,,;:::::::::;;;;;;;;,,;:oOKXNNNNNWWWWWWWWWNNNNNNNX0dclONMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXxodkxxxkkxxxxxdolc:;,,'',,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,,,;:::::::::::;;;;;;;;;;;;;;;;;;;;;;;,,'..........',;;;;,,;;;;;;;;;;;;,'......',;;;;;;;:::::cc:::::;;;;;;;;;;;;;,,,;::::::::::;;;;;;;;;,,;cdOXNNNNNNNNNNNNNNNNNNXKOxooONMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWXkooddollcc:;;,,'''',,,;,,;;;;;,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,,,,;::::::::::;;;;;;;;;;;;;;;;;;;;;;;;,,'...........'',;;;;;;;;;;;;;;;;;,'.......',;;;;;;;;::::::::::;;;;;;;;;;;;;;,,,;:::::::::::;;;;;;;,,,,,:ldO0XXNNNNNNNNNNNNXKOkxxddONMWMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNNXK0Oxdoc;;,''''.''''',,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,,,,;;::::::::::;;;;;;;;;;;;;;;;;;;;;;;;;,'.............',;;;;;;;;;;;;;;;;,'........',,;;;;;;;;;:::::::;;;;;;;;;;;;;;;;,,,;::::::::::::;;;;;,,;;;;,,;:ldxO0KXXXXXXKK0OkxxxxdoONWMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNKOxdlc:;,'''....''''',,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,,,,;;:::::::::;;;;;;;;;;;;;;;;;;;;;;;;;,,''..............',;;;;;;;;;;;;;;,''.........',;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,,;;::::::::::::;;;;;;;;;;;,,,,;:cloxkkkOkkkkxkkkxxddOWMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMWMWWWX0ko:;,'.......'''',,,,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,;;;;;;;;;;;;;;;;;;,,,,,;;;::::::::;;;;;;;;;;;;;;;;;;;;;;;;;;,,''................',,;;;;;;;;;;;,''...........'',;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,,;;::::::::::::;;;;;;,;;;;,;;;,,,,;;:clodxxxxxkxkkddKWMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMWWWNKko:,........''''',,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,,,,,,;;;;;;;;;;;;;;;,,,,,;;;:::::::::;;;;;;;;;;;;;;;;;;;;;;;;;,,'''..................'',,,,;;;;,,,'...............',,;;;;;;;;;;,;;;;;;;;;;;;;;;;;;;;,,,;;;::::::::::::;;;;;;;;;;;;;;;;;;,,,,;;:cloodxxxxdONMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMWWN0xl;'.......''',,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,,,,,,,;;;;;;;;;;;;;;;;,,,,,;;;::::::::::;;;;;;;;;;;;;;;;;;;;;;;;;;,'........................'''''''''..................',,;;;;;;;;,',,;;;;;;;;;;;;;;;;;;;,,,,;;:::::::::::::;;;;;;;;;;;;;;;;;;;;;;;,,;;;:clookXWMMWMMWMMMMM
MMMMMMMMMMMMMMMWMMMWWWWKkl;''.....''',,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,,,,,,,,,,,;;;;;;;;;;;;;;;;;,,,,,;;;::::::::::;;;;;;;;;;;;;;;;;;;;;;;;;;,,'.....................................................',,,;;;;;,,'',;;;;;;;;;;;;;;;;;;;;;,,,;;::::::::::::::::;;;;;;;;;;;;;;;;;;;;;;,,;,,;;cx0XWWWWWMMMMM
MMMMMMMMMMMMMMMMMWWWNKx:'.....''',,,,;;;;;;;;;;;;;;;;;;;;;,,;;;;;;;,,,,,,,,,,,,;;;;,;;;;;;;;;;;;;;;,,,,,,;;;:::::::::;;;;;;;;;;;;;;;;;;;;;;;;;;;;,'................................'',;:cllc::::;'........',,;;;;;,'..',,;;;;;;;;;;;;;;;;;;;;,,,;;;:::::::::::::::::;;;;;;;;;;;;;;;;;;;;;;;;,,,;:lx0NWWWMMMM
MMMMMMMMMMMMMMWWWWNKx:'.....'',,,;;;;;;,,,,,,,,;,,,,,,,,,,,,,,,,,,,,,,,,,,;;;;;;;;;;;;;;;;;;;;;;,,,,,,,;;;;;::::::;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,,'............................',:ldkO0KXXNKO0KXK0kxoc;'....'',,,,,'....',,;;;;;;;;;;;;;;;;;;;;,,,,;;;;::::::::::::::::::;;;;;;;;;;;;;;;;;;;;;;;;,,,:okXWMMMM
MMMMMMMMMMMMMMMWWXkc'......',,,,;,,,,,,,,,'''''''''''''''.....'',,,,;;;;;;;;;;;;;;;;;;;;;;;;;,,,,,,,;;;;;;;;::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,''.........................',:ox0XNWWWWNNNN0kKNNNNNNNX0ko:,...''''''.....',,;;;;;;;;;;;;;;;;;;;;;,,,,;;;;::::::::::::::::::::::::;;;;;;;;;;;;;;,;;;,;,;lkXWWW
MMMMMMMMWWMMMMWN0o,........''''''''''........................',,,;;;;;;;;;;;;;;;;;;;;;;;;;;,,,,,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,'''.......................';lxOXNWWWWWWWWWWN0k0NWWWWWWWWNNXKkl,...'........'',,;;;;;;;;;;;;;;;;;;;;;,,,,;;;;;;:::::::::::::::::::::::::;;;;;;;;;;;;;;;;;;,;lONW
MMMMMMMMMWWWWWXx:...........................................',,;;;;;;;;;;;;;;;;;;;;;;;;;,,,,,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,,''.......................',lx0XWWWWWWWWWWWWWN0k0NWWWWWWWWWWWNNNKkc'............',,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:::::::::::::::::::::::::;;;;;;;;;;;;;;;;;;,:dK
MMMMMMMMMMMWWKo,...........................................',;;;;;;;;;;;;;;;;;;;;;;;;,,,,,,,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,'''......................',cd0XWWWWWWWWWWWWWWWXOkKNWNWWWWWWWWWWNNNNNKxc,'..........''',,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;::::::::::::::::::::;;;;;;;;;;;;;;;;;;;;,,c
MMMMMMMMMMMW0l,............................................',;;;;;;;;;;;;;;;;;;;,,,,'''',,;,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,,''.......................,:dOXNWWWWWWWWWWWWWWWNKkOKNNNNNWWWWWWWWWNNNNNNNKkdc:;,,''.......'',,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:::::::::;;;;;;;;;;,,;;;;;;;;;;;;;,,
MMMMMMMMMMW0l'..................''',,,,;;:;;;,'.............',,;;;;;;;;;;;,,,,,'''......'',,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,''.......................':oOKNWWWWWWWWWWWWWWWWWXOkOXNNXXKK0000KKKXXNNNNNNNNNXXK0OOkdl;'.......'',,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,
MMMMMMMMWWKo,.............'',;:clooddxxxxxxxxdolc;,..........'',,,;,,,,,,,'''............'',,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,,,'.......................';lx0XNNNWWWWWWWWNNNXXXNNXOk0XNX0OkkkkkkkkkkkOO0KKXXNNNNNNNXNNNX0kc,.......'',,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,,,,,,,;;;;;;;;;;;;;;
MMMMMMMMMXx,........',:loc:ldxkkkkkkOOOOOkkkkkxxkxdl:,'.........'''''''.....................'''',,,,,;;;;;;;;;;;;;;;;;;;,,,,''''.....................'',cdOKXNNNNNNNXXKK00OkkkkkOOxx0XK0OkxxkkkkkkxxkkkkkkkOO00KKXXXXNNXNNNXkc,'.....'',,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,,,,,,,,;;;;;;:cloooddc:cc:;,;;;;;;;;
MMMMMMMWWO:......,:okOOxl;;lk000KKKXXXXXXXK00Okxxxxxxdl:;,'......................................''''',,,,,,,,,,,,,,,,''''.........................':odkKXNNXNNNXK0OOkkkkxxxxxxxold0K0OkxkxxxkkkkkxkkxkkkkkxkkkkkkOOO00KXNXKOkkxl;'...'',,;;;;;;;;;;;;;;;;;;;;;;;;;;:cllc::;;,:ccllodxk0Ok0XXOxO0Oxoc;;;;;;;
MMMMMMWWXo'...',lkKXKkl:;;;oKNXNNNNNNNNNNNNNXXK0kxddxxxxxdollllllcc:,'....................................'''''''...............................';lx0XXNNNXNNXK0Okkxkkkkkxxxdddxdd0K0kxxxkxkkkxxxkxxxxxxxxkkkxxxkkkkkkkkOOOkOXNWX0xc,'.'',,;;;;;;;;;;;;;;;;;;;;;,;cx0KXX0kxdlcoxxxxxxk0OkOKNN0xkXWWNKko:,,;;
MMMMMMWWO:..';o0XNXOo::::::lOXNNNNNNNNNNNNNNNNNXKOdodkkxxkkxxkkxxxxxdl;......................................................................',:d0XXNNNNNNNXX0kkkkkkkkkxxxdooxOOxk0OkxxkkxxxkxkkkkxdooxxxxkkxxxxkkxxxxdddxOXNWWWWWWX0dc;,'',;;,;;;;;;;;;;;;;;;,;:d0XNXNNNKOkocoxkxkkkOOk0XNNN0xx0WMWWWNOo:,,
MMMMMMWWk,.;o0NWN0dc:ccc::::o0XNNNNNNNNNNNNNNNNXX0dodxxxkkkkkkkxxxkxxxo:'.................................................................',:okKXNXXXXXXXXX0OkxkkkkkkkxxxxxxxkkdxOOkkkkkkxxxxxxxxxkkdoodxxxxxddxddxxxkO0KNWWWWWWWMMMWWNKOxl,'',,,;;;;;;;;;;;,;:oOXNNNNNNNXKkocdxxxkkOkkKXNNNX0xd0NMWWWWWNOl;
MMMMMMWWx;cONWWNOl::cccccc:::d0XNNNNNNNNNNNNNNNNNKxooxkOO00000OOkkkkkkxd:'..............................................................,:ox0KKKK00OOOkkOOkxxxxkkxxkkxxxxxkkxxxodkkxxkkkkkkkxdodkkkxkxdoodddxkO0KKXXNWWMMWWMMMMMMMMMMMMMWXd,..,;;,,,,,,,,,;clx0XNNNNNNNNNNXOolxxkkkkxOXNNNNNKOdoONMMMMMMWWXx
MMMMMMMWKkKWWWNkc:ccllllccc:::lOXNNNNNNNNNNNNNNNNXkodOKXXNNNNNXXXK0Okkxxd:'..........................................................',cokOOkkxdollcc:::::::cdddoollcccccccloooldkxxddoooooddoloxdddddxxdooxKNWMMMMMMMMMMMMMMMMMMMMMMMMWW0c'..,loolc:clodxO0XNNNNNNNNNNNNNXKkxkkkkxkKXNNXNNKOkddONMMMMMMWWWW
MMMMMMMMWWWWWNkc:clllllllcc:::;:d0XNNNNNNNNNNNNNNXXKKXNNNNNNNNNNNNNX0Okkxd:'........................................................,:loollc:;;,,,,,,,,,,,,,,;;;,,,,,,;;;,,,;,,,:c::;;,,,,,;;;,;:;;;;;:cldkXWWMMMMMMMMMMMMMMMMMMMMMMMMMMNk;...':dxkxxxOKXNNNNNNNNNNNNNNNNNNNK0000kOXNNNNNXKOkxxdONMMMMMMMWWW
MMMMMMMMMWWWNOl:clllllllllcc:::;;cd0XNNNNNNNNNNXNNNNNNXNNNNNNNNNNNNNNX0Okxdc;'..................................................'',,,,,,,,,,,,,,;;;;;;;;;;,;;,;;;;,;;;;;;;;;;,''',,,;;;;;;;;,,,,,;;;;;,,:xXWWWWMMMMMMMMMMMMMMMMMMMMMMMMMXd,....':dxkkO0XXNNNNNNNNNNNNNNNNNNNNXXXKKXNNNNNXK0kxxxdONMMMMMMMMWW
MMMMMMMMWWWWKd:ccllloollllccc::;;;;cd0XNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXK0Okxdl;,'.........................................'''',,,;;;;;;;;;;;,,'',,,,,;;;;;;;;;;;;;;;;;;;;;;;;,'',;;;;;;;;;;;;;;;;;;;;;;;:kNWWWWMMMMMMMMMMMMMMMMMMMMMMMMMXd,.....'cdkOKXXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXK0kxxxxoxXWMMMMMMMMM
MMMMMMMMMMWXxc:clllllolllllcc::::;;;;:oOKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXK0Okxxoc;;,'..............................'''',,,,,,;;;;;;;;;,;;;;;;;,,,,,,,,,,,,,,;;;;;;;;;;;;;;;;;,'',;;;;;;;;;;;;;;;;;;;;;;;;dXWWMMMMMMMMMMMMMMMMMMMMMMMMMMWXx,......':xKNXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXKOkxkxxxdd0WMMMMMMMMM
MMMMMMMMMWN0l::cllllllllllccc::::;;;;,,;cx0XNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXKK0kdx0KKOxdoollllllllllooooddxxdlc;,,,,;;;;;;;,,,,,;;;;;;;,;;;;;;;;;;;;;,,,,,,,,,,;;;;;;;;;;;;;;;,'',;;;;;;;;;;;;;;;;;;;;;;,,l0NWMMMMMMMMMMMMMMMMMMMMMMMMMMWNO:'......'cOXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNX0OkxkkxxxddONWMMMMMMMM
MMMMMMMMMWXx::cclllllllllcc::::;;;;;,;;,,,:lx0KXNNNNNNNNNNNNNNNNNNNNNNNNNNNNKOOKNWWWWWWWWWWWWWWWWWWWWWWWWWWWWNKxc;,;;,,,,,,,,;,;;;;;;;;;;;;;;;;;;;;:::::::::;;,,,,,;;;;;;;;;;;,',;;;;;;;;;;;;;;;;;;;;;;;,:dKWWWWWWWMMMMMMMMMMMMMMMMMMMMMWXd,.......';d0XNNNNNNNNNNNNNNNNNNNNNNNNNNNXK0kkkkkkkkxolxXWMWMMMMMM
MMMMMMMMWW0c;:ccllllllllcc:::;;;;;,,;;;;;;;,;:lxOKXNNNNNNNNNNNNNNNNNNNNNNNXXOkXWWWWWWMMMMMMMMMMMMMMMMMMMMMWMWWWNk:,,,,,,,,,;;;;;;;;;;;;;;;;;;;;;:::ccccclllllcc:;;,,,,;;;;;;;,'.',;;;,;;;;;;;;;;;;;,,,,,,',ldxxxxkkOO0KXXXNNWWMMMMMMMMMMMW0c'......',,cx0XNNNNNNNNNNNNNNNNNNNNNNNNX0Okxkkkkkkxl;,lKWWMMMMMMM
MMMMMMMWWXx:;cclllllllccc::;;;;;;;;;;;;;;;;;;;,,;cldk0KXNNNNNXNNNNNNNNXXXXK0kxO000000000000KKXXNNNWWWWMMMMWMWWWNk:''',,;;;;;;;;;;;;;;;;;;;;;;;;:::clloooooooooollc:;,,,,,,;,,''..',;,,,;;;;;;;;;,,,'',,,,,,,,,;;;;;;:::ccclodxO0XNWWWMMMMWXx,......',,,;cd0XNNNNNNNNNNNNNNNNNNNNXKOkkkkkkkxdl;'.,dXWWMMMMMMM
MMMMMMMWW0l;:clllllllccc::;;;;,;;;;;;;;;;;;;;;;;,,,;;;:loxkO0KKKKKK0Okxdolc:;;:;;;;;;;;;;;;::ccclodkO0KNWWWWWWN0o,,;;,;;;;;;;;;;;;;;;;;;;;;;;;;::clloooddddddddoollcc;,''''''.....',,;;;;;;;,,''',,,;;;;;;;,;;;;;;;;;;,,;;;,,;;;:ldOKNWWWWW0:......',,,,,,:okKXNNNNNNNNNNNNNNNXK0kkxxxxxdoc,'..'l0NWWMMMMMMM
MMMMMMMWNk:;cclllllllcc:;;;;;,,,;;;;;;;;;;;;;;;,,;;;;;,,,,,,;:::::::;;,,;;;;;;;;;;::::::::::::::;;;;::cloxO0K0xc;,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:cclooooddddddddooollcc;,'.........''',,,,,''',,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,,,;:ldOKNN0c......',;;,,,,,;cokOKXNNNNNNNNNXK0kkxxxdoc:,'...';dKWWWWWMMMMMM
MMMMMMMWKo::cllllllccc::;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,,,,,',,,,;;;;;;:::::::::::::::::::::::::::::::::;;;;;:c:;,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:ccllooodddddddoooolllc:;,'.............'',,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,,,;cldo;.......',;;;;;;;,,;:codxkO00K00Oxddolc:,'......,lONWMMMWMMMMMMM
MMMMMMWNk::cllllllcc:::;;;;;;;;;;;;;;;;;;;;;;;;;,,,,'',,,;;;::::::::::::::::::::::::::::::::::::::::::;;;;,'',,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:cccllloooooooooooolllcc:;,'..........',,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,,,,''.'''''''',,,,,,;;;;;;;;;;;;:;;;;;,,''........,lOXWMMMMMMMMMMMMM
MMMMMWNOc:clllllccc::;;;;;;;;;;;;;;;;;;;;;;;;,,,,'',;;;:::::::::::::::::::::::::::::::::::::::::;;;;;;;;;,',,;;;;;;;;;;,;;;;;;;;;;;;;;;;;;;;;;;;;;;::::ccclllllooooooollllc::;''......',;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,,'',;;;;;,,,,,,,,,,,,,,,'''................,ckNWWWMMMMMMMMMMMMM
MMMMWNOl:ccccllccc::;;;;;;;;;;;;;;;;;;;;;;,,,,,,;;::::::::ccc:::::::::::::::;;;;;;;;;;;;;;;;;;;;;;;;;;;,,,,;;;;;;;;;;;;,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;::::cccclllllllolllc::;,'...',,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:::::;;;;,,'',;;::::::::;;,,'''..................;oOXWWWWWMMMMMMMMMMMMM
MMMWNOl:::cccccc::;;;;;;;;;;;;;;;;;;;;,,,,,,;;:::::::cccc::::::;;;;;;;;;;;;;;;;;;;;;;;;;;;,,,;;;;;;;;;;,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:::::ccclllllllc::;,'.',,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;::ccllccc:::;;,,',;:ccccccccc:::;;,'.............':d0NWWWWMMWMMMMMMMMMMMMM
MWWXkc;:::::::::;;;;;;;;;;;;;;;;;;;;,,',,;:::::::c::::::::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:::ccllllllcc:;;,'',;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;::clooooollc:;;;;;,,;::cccccccccccc::;,'........,ckKNWMMMMMMMMMMMMMMMMMMMMM
WWKx:;::::::::;;;;;;;;;;;;;;;;;;;,,,',;;:::::cccc::::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;::cccllllc::;;,'',;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:loodddoollc:;;;;;,',;::cccclllllcccc::;'....'cxXWWWWMMMMMMMMMMMMMMMMMMMMM
N0o;;;;;;;;;;;;;;;;;;;;;;;;;;;,,,,,,;:::::::::::::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;::ccllllc::;;,'',,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;::cloooooollc:;;;;;;,,,;:::ccccccllllcccc::,',o0NWWWWWMMMMMMMMMMMMMMMMMMMMM
kc;;;;;;;;;;;;;;;;;;;;;;;;;;,,,,,;:::::cc:::::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;::ccclccc:;;;,,',,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:cclllllllc::;;;;;;;,,,,;:::c:cccccllcccccc::cxKNWWWMMMMMMMMMMMMMMMMMMMMMM
:;,;;;;;;;;;;;;;;;;;;;;;;;,,,,;;:::::::::::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;::ccccc::;;;,'',,,;;;;;;;;;;;;;;;;;,;;;;;;;;;;;;;;;;;;;;;:::ccccc::;;;;;;;;;;,,',;;::::::cccccccccccc::cxKWWWMMMMMMMMMMMMMMMMMMMMM
,;;;;;;;;;;;;;;;;;;;;;,,,,,,;::::::::::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;::cccc::;;;,'',,;;;;;;;;;;;;;;;;,,,;;;;;;;;;;;;;;;;;;;;;;;;;:;;;;;;;;;;;;;;;,,',;;;;;;:::ccccccllcccc::lOXWMMMMMMMMMMMMMMMMMMMMM
;;;;;;;;;;;;;;;;;;;;;,,',,;:::::::::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;::::c::;;;;,'',;;;;;;;;;;;;;;;;,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,',,;;;;;;;:::cccccllllccc::dKWMMMMMMMMMMMMMMMMMMMM
;;;;;;;;;;;;;;;;;;;,,,,;:::::::;;:;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:::::;;;;;,',;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,',;;;;;;;;;;:::cccclllccc::o0NWMMMMMMMMMMMMMMMMMM
;;;;;;;;;;;;;;;;;,,',;;:::::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:::::;;;;,'',;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,'',;;;;;;;;;;;::::cclllccc::lOXWWWWMMMMMMMMMMMMMM
;;;;;;;;;;;;;;;;,,,,;;:::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,'',;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:::::;;;;,,',;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,'';;;;;;;;;;;;;;:::ccccc:::;ckNWWMMMMMMMMMMMMMMM
;;;;;;;;;;;;;,,'',;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,''',;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;::::;;;;,,',,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,'',;;;;;;;;;;;;;;;::::::::;,,cONWMMMMMMMMMMMMMMM
;;;;;;;;;;;,,,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,'..',;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;::::;;;;;,'',,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,'',;;;;;;;;;;;;;;;;;;;;;;;,'',l0WWWMMMMMMMMMMMMM
,,'''''''''',;;:::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,'..',,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;::::;;;;;,'',;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,',;;;;;;;;;;;;;;;;;;;;;,''',,,lKWWMMMMMMMMMMMMM
''.......';:ccc:::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,'...',,;;,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:::;;,;;,,'',;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,',;;;;;;;;;;;;;;;;;;;,,'..',,,,lONWMMMMMMMMMMMM
......';:ccllccc::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,''...',;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;::;;;;;;,'.',;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,'';;;;;;;;;;;;;;;;,,,'...',;;;;,ckNWMMMMMMMMMMM
....';:cllllllcc::;;;;,,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,''...',;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,'.',;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,'',;;;;;;;;;;;,,,,'''...',,;,;;,;lONMMMMMMMMMMM
...,:clllllllcc::;;;;;,'',,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,'.....,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,'..',;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,'',;;;;;;,,,,,'''.......',;;;;;;,:xNMMMMMMMMMMM
..':clllllllcc::;;;;;;,,'''',,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,'.....';;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,''..',;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,'',,,,,,''''............',,;;;;;,;xXMMMMMMMMMMM
.';clllllllcc::;;;;;;;;,''..''''',,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,'.....',;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,'...',;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,..'''.................''',,,;;;;,:xXWMMMMMMMMMM
.':cllllllcc::;;;;;;;;;;,,,'''''...''''''',,,,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,'.....';;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,'....',;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;'....................'',,,,;;;;;;,;dXWMMMMMMMMMM
.':cllllllcc:;;;;;;;;;;;;;;;;;;,,,,,'''''......'''''''''',,'''''''''',,,,,,,,,,,,,,,,,,,,,;;;;;;;;;;;;;;;;;;;;;;;,'.....',;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,'.....',;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,'...................'',;;;;;;,,;;,,l0NWMMMMMMMMM
'';cllllllcc:;;;;;;;;;;;;;;;;;;;;;;;;;,,,,,,,,''''....''.............................'''''',,,,,;;;;;;;;;;;;;;;;;;,''....',;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,'......',;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,...................',,,;;;;;;;;;;;;ckNWWMMMMMMMM
ko;;clllllcc::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,;cdxdolc::;;,'''...........................''',,,;;;;;;;;;;;;;;;,,'...',;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,'......',,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,',;;::::cc:,'''',,,,;;;;;;;;;;;;;;,:kNWWMMMMMMMM
WKo;:lllllcc::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,;oOKXNXXXK00Okxddollc:;,''......................'''',,;;;;;;;;;;;;;,,''..,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,'.......',,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,cddxxxxxkkkkxl;,,,;;;;;;;;;;;;;;;,;oKWWMMMMMMMMM
MNO:;:ccllcc::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,;oOXNNNNNNNNNNNXXXKKK0Okkxdolc:,'.....................'',,,;;;;;;;;;;;,,,'.',,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,''........',;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,;oxkkkkkO0KXNXKkl,,;;;;;;;;;;;;;;,:dKWMMMMMMMMMMM
MWXd;;:cccccc::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,;ckXNNNNNNNNNNNNNNNNNNNNXXXK0OOkkxdlc;,''..................'',;;;;;;;;;;;,;;,,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,''.........',;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,;lxxkkO0KXNXNNNNX0o;,;;;;;;;;;;;,;lOXWMMMMMMMMMMMM
MWW0l,,:cccc:::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:o0XNNNNNNNNNNNNNNNNNNNNNNNNNNXXKK0OOkxdolc;,'................'',,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,''..........',,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,cdxk0KXXNNNNNNNNNNKd;,;;;;;;;;;:oOXWWMMMMMMMMMMMMM
WWWNOc,,::::::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:dKNNNNNNNWWNNNNNNNNNNNNNNNNNNNNNNNNXKK00Okkxdlc;,'..............'',,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,''.............',;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,,:dkO0XNNNNNNNNNNNNNX0l,,;;;;;;:o0NWWMMMMMMMMMMMMMMM
MWWWNOc',;;;;;;;;;,,;;;;;;;;;;;;;;;;;;;;,;:xKNNNNWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNXKK0Okxxxdol:,'............'',,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,''...............'',;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,;;,,,'';oxOKNNNNNNNNNNNNNNNXXk:,,;,,;ckXWMMWMMMMMMMMMMMMMMM
MMMMWNOc'',;;;;;;,,,,;;;;;;;;;;;;;;;;;;;,;dKNNNWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNXXK0Okkkkkxoc;,...........'',,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,,'''..................'',;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,,'..';lx0KXNNNNNNNNNNNNNNNNN0o;,,;:xKWMMMMMMMMMMMMMMMMMMMM
MMMMMMW0l,'',,;;,,'',;;;;;;;;;;;;,;;;;;,;oKNNNNWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNXXXK0Okkxxxxol:;''........'',,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,,''''......................'',;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,,,'...':ok0XXNNNNNNNNNNNNNNNNNNKx:;lxKNWWMMMWMMMMMMMMMMMMMMMM
MMMMMMMWXkc'.'''''..',,;;;;;;;;;;;;;;;,,l0NNNNNWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNXK0Okxxxxxxdoc;'........''',,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,,,'''''............................'',,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,,'''.....'cdO0XNNNNNNNNNNNNNNNNNNXKOxokKWWMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMWKx:'.......',,,;;;;;;;;;;;;;,cOXNXNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNXXK0Okkkkkkxdl;'.........''''',,,,;;;,,;;;;;;;;;;;;;,,,,''''.................',:;'...............'''',,,,;;;;;;;;;;;;;;;;;;;;;;;;;,;;;,,,''.........;lk0KXNNNNNNNNNXNNNNNNNX0Ok0KXNWMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMWWWXko:,'.....'',,;;;;;;;;;;,;dXNNNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNXXK0Okxkkxxdo:;'............'''''''''''''''''''''''.....................,:oOKOo;'..................'''''',,,,,,,,,,,,,,,,,,,,,,'''''..........',cdkKXNNNNNNNNNNNNNXNNXK0Ok0NWWWMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMWMMMWWNXOxoc:,'..'',;;;;;;;;;,cONNNNNNNNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNXX0OOkkxxxxdl:,'..................................................':okKNWWWNOo;..........................'''''''''''''''.................',cdO0XNNNNNNNNNNNNNNNXXKOO0KNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMWNNX0x:'..'',,;;;;;;;oKNNNNNNNNNNNNNNNNNNWWNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNXK00Okkkkxxdo:,'............................................,cokKNWWWWMMMWNOo;.....................................................',;lxO0XNNNNNNNNNNNNXNNNKOOOKNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMWNKd;'..'',;,;;,;dKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXK0Okkkxxxxdoc;,'...................................',:ox0XWWMMMMMMMMMMWWN0d:'..............................................'',:ldkOKXXNNNNNNNNNNNNNNX0kk0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMWWWN0d:'..''',,';d0KXXXXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXNNNNNXXKK0Okkkkkxxdoc:;,''.......................',;:ldk0XWWWWWMMMMMMMMMMMMWWWWXkl;'........................................',:coxk0KXXNNNNNNNNNNNNNNXKOOOKNWMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMWWWWNKxc'......;okkOO000KKKXXXXXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXXNKKXXXXNNXXNNNXXK0OOkkkkkkxxdolc::;,,,''''''''''';:cldxOKXNWWMMMMWWWMMMMMMMMMMMMWWWWXOxolc;,''.............................'',;:codxkO0KXNNNNNNNNNNNNNXX0OOOKXNWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMWWMMWWWKxc,....;oxkkkkkkkkkkOOO0000KKKKKXXXXXNNNNNNNNNNNNNNNNNNNNNNNNNNXNXOOXXOOX0O0NNXXNNNNNNNXXK00OkkxxxkkkxxxdddoooooooooooodxOXWWWWMMMMMMMMMMMMMMMMMMMMMWWWXOdddxxxxdolc:;;,''''...........'',,,;;:cloddxkkO0KXXNNNNNNNNNNNNNX0OOO0XNWWMMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWXOd:;,:odxxxkkkkkkkkkkkkkkkkkkkkOOOOOO0000KKKKKKXXXXXXXXXXXXXXXXKxx00k00xkXNNNNNNNNNNNNNNNXXK0OOkkkkkkkkkkkkxxkkkkxkkxdood0WWWWWMMMMMMMMMMMMMMMMMMWWWKxoxxkkkkkkkkxxxxddooolllllllllloooddxxxxxxkkO0KXXXNNNNNNNNNNNNXKOkkOKNWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNKK00OkxxxxxxxxxxxxxxxxkxxkkxkkkkxxkkkkkkkkkkkkkOOOOOOOOOOOOOkoloddOxd0NXNNNNNNNNNNNNNNNNNNXXK0Okkxxxkkkkkkxxxxxxxxxxxdd0NWWWMMMMMMMMMMMMMMMMMMMN0ddxkkkkkkkkkkxxxxkxdoddxxkkkkkkxxkkkkkkkOO0KKXNXXXNNNNNXNNXXK0OOO0XNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMWWWMMWWNXK00Okkxxxxddxdddddddxxxxxxxxxkkkxxxkkxxxkkkxxxxxxxxxxdl::odllkKXXXNNNNNNNNNNNNNNNNNNNNXK0OkxxxkxdooooodxxkkkkxdxKWWMMMMMMMMMMMMMMMMMMMW0ddxxxkkkkkkkkkxkkkkkxdooodxkkkkkkkOOO00KKXXXNNNXK0XNNNNNNXK0OO0KNWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMMMMMMMMMMMWWWNNNXXKKK0000Okkkkxxxxxdddddddddddddxddddddddddxxdlcll:lk0KXNNNNNNNNNNNNNNNXNNNNNNNXX0kdolooodddxxxkkkkkxxdkXWMMMMMMMMMMMMMMMMMMWXkdxxkkkkkkkkkkkkxkkkkxxxxdoox0KKKXXXXXNNNNNNNNNNXOx0NNNXKOOO0XNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWNNNXXKKKKKKKKKKKKKKKKKKKKXXNNNNX0kllOXXNNNNNNNNNNNNNNNNNNNNNNNNXKOdlodxxxkkkkkkkkkxxkxdxXWMMMMMMMMMMMMMMMMMMWKxdxxkkkkkkkkkkkkxxkkxxxxxxxdoxKXNNNNNNNNNNNNNNNNXKxkKK0OkOKNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0dOXNNXNNNNNNNNNNNNNNNNNNNNX0kdddxxxxxkxxkkkkkkkkkkxdxKWMMMMMMMMMMMMMMMMMMWKxdxxxkkkkkkkkkkkkkkkkkkxxxxxxox0XNNNNNNNNNNNNXNX0OxodO0KNWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOkKNNNNNNNNNNNNNNNNNNNNNNKxdddxxkkkxkkxxkkkkkkxxxkxdkNWWMMMMMMMMMMMMMMMMMWKxdxxxkkkkkkkkkkkkkkkkkkkxxxkkxoxKXNNNNNNNNNNNNXX0dooONWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXkOXNNNNNNNNNNNNNNNNNNNXOdoxxxkkkkkkxxkkkkkkkkkxxxdxKWMMMMMMMMMMMMMMMMMMMWXxdxkxkkkkkkkkkkkkkkkkkkkkkkkkkdoxKXNNNNNNNNNNNNNXOdONWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0kKNNNNNNNNNNNNNNNNNNKxodxkkkkkkkkkkkkkkkkkkxkkxxdONWMMMMMMMMMMMMMMMMMMMWNOdxkkkkkkkkkkkkkkkkkkkkkkkkkkkxdokXNNNNNNNNNNNNNNXOxKWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKk0NNNNNNNNNNNNNNNNX0dodxkkkkkkkkkkkkkxkkkxxkxxddkNWMMMMMMMMMMMMMMMMMMMMMWKxdxkkkkkkkkkkkkkkkkkkkkkkkkkkkxod0XXNNNNNNNNNNNNNXOk0NWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXkOXNNNNNNNNNNNNNNX0ddxkxkkkkxkkkkkkkkkkkkxxxdodONWWMMMMMMMMMMMMMMMMMMMMMMW0ddxkkkkkkkkkkkkkkkkkkkkkkkkkkkdodKNXNNNNNNNNNNNNNX0k0NWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXkkKNNNNNNNNNNNNNX0doxxxxxxkkkkkkkkkkkkkkkxdoxk0NWMMMMMMMMMMMMMMMMMMMMMMMMWNOodxkxkkkkkkkkkkkkkkkkkkkkkkkkkdokXNNNNNNNNNNNNNNNX0k0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNOkKNNNNNNNNNNNNXKxoxxkkkkkkkkkkkkkkkkkkkxddkXWWMMMMMMMMMMMMMMMMMMMMMMMMMWWWNOooxxkxkkkkkkkkkkkkkkkkkkkkkxkxooOXNNNNNNNNNNNNNNNX0k0NWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOOKNNNNNNNNNNNXKkodxkkkkkkkkkkkkkkkkkkxxdx0NWWMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWN0xoxxkkkkkkkkkkkkkkkkkkkkkkxxkxoo0XNNNNNNNNNNNNNNNN0kOXWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNOOKNNNNNNNNNNNXkodxkxkkkkkkkkkkkkkkkkxddOXWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWXkddxkkkkkkkkkkkkkkkkkkkkkkkxxxod0XNNXXNNNNNNNNNNNNKkkXWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNKkOXNNNNNNNNNNXOooxkkkkkkkkkkkkkkkxxkxod0NWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWN0xodxxkkkkkkkkkkkkkkkkkkkkkxxxod0XNNXNNNNNNNNNNNNNKkkKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMWKkOXNNNNNNNNNNN0ooxkkkkkkkkkkkxxxkkkxdoxXWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWXOxddxkkkkkkkkkkkkkkkkkkkkkkxxox0XNNNNNNNNNNNNNNNNXOkKWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNOk0XNNNNNNNNNNX0doxkkkkkkkkkkkkkkkkkxddONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWX0xodxkkkkkkkkkkkkkkkkkkkkkkxod0XNNNNNNNNNNNNNNNNXOk0NWWWMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKkkKNNNNNNNNNNNN0doxkkkkkkkkkkkkkkkxxxdd0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWX0xddxkkkxkkkkkkkkkkkkkkkkxxodOXNNNNNNNNNNNNNNNNX0OOKNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNKOk0XXNNNNNNNNNNNKxdxkkkkkkkkkkkkkkkkkxddONWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWXOxdxkkkkkkkkkkkkkkkkkkkkkxdoxKNNNNNNNNNNNNNNNNXX0OOKNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWNWNNNNNXKK0OO0XNNNNNNNNNNNNXKxoxxkkkkkkkkkkkkkkkkxxdkXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKkddxkkkkkkkkkkkkkkkkkkkkkdod0XNNNNNNNNNNNNNNNNXX0kk0KNWWMMWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWNX00O0OOO0000KKXNNNNNNNNNNNNNX0xodxxxkkkkkkkkkkkkkxxxdd0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMWNOddxkkkkkkkkkkkkkkkkkkkxxxddkKXXNNNNNNNNNNNNNNNNXK0OO00KXNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNKOOO0KKKXXXNNNNNNNNNNNNNNNNNNNXKxodxxxxkkkkkkkkkkkkkkkxdxXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWW0doxkkkkkkkkkkkkkkkkkkkkkxxddOKXNNNNNNNNNNNNNNNNNNXXK00OO0XWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWX0kO0XNNNNNNNNNNNNNNNNNNNNNNNNNNX0xoxkkkkkkkkkkkkkkkkkkkkxdxXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKdoxxkkxxkkkkkkkkkkkxxxkkxxdddkKXNNNNNNNNNNNNNNNNNNNXXXKOk0NWMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWNKkOKNNNNNNNNNNNNNNNNNNNNNNNNNNNNXOdoxkkkkkkkkkkkkkkkkkkkkkxdxKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0ddxkkxxkkkkkkkkkkkkkkkkkkkxdoodk0KXNNNNNNNNNNNNNNNNNNNX0kONWMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
areyousure?MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWNXOk0XNNNNNNNNNNNNNNNNNNNNNNNNNNXXOxodxkxkkxxkkkkkkkkkkkkkkkkxdd0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXkdxkkxxkkkkkkkkkkkkkkkkkkkkkxxddodxkO0KXXXNNNNNNNNNNNNNXOkKWMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMN0kk0XNXNNNNNNNNNNNNNNNNNNNNNNNNNKOdodxkxkkxkkkkkkkkkkkkkkkkkxxdd0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOdxkkkkxkkkkkkkkkkkkkkkkkkkkkkkxxddooodxkO0KXXXNNNNNNNNNKk0NWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM

  ____  __  ____  ________  ______   _  __  
 / __ \/  |/  / |/ /  _/  |/  / _ | / |/ /  
/ /_/ / /|_/ /    // // /|_/ / __ |/    /   
\____/_/  /_/_/|_/___/_/  /_/_/ |_/_/|_/          
                     
]]

-- Omni Man SWEP
-- Created by: jopster1336
-- Animations by: Killer-Rabbid306

CreateConVar("omniman_cfg_superflight_sensitivity", "0.3", {FCVAR_ARCHIVE, FCVAR_REPLICATED, FCVAR_PROTECTED, FCVAR_SERVER_CAN_EXECUTE} )
CreateConVar("omniman_cfg_damagemul", "1", {FCVAR_ARCHIVE, FCVAR_REPLICATED, FCVAR_PROTECTED, FCVAR_SERVER_CAN_EXECUTE} )
CreateConVar("omniman_cfg_defaulthealth", "30000", {FCVAR_ARCHIVE, FCVAR_REPLICATED, FCVAR_PROTECTED, FCVAR_SERVER_CAN_EXECUTE} )
CreateConVar("omniman_cfg_superarmormul", "1", {FCVAR_ARCHIVE, FCVAR_REPLICATED, FCVAR_PROTECTED, FCVAR_SERVER_CAN_EXECUTE} )
CreateConVar("omniman_cfg_regenenabled", "1", {FCVAR_ARCHIVE, FCVAR_REPLICATED, FCVAR_PROTECTED, FCVAR_SERVER_CAN_EXECUTE} )

-- CreateClientConVar("omniman_thirdperson_enabled", 0, true, false, "Enable thirdperson", 0, 1)
CreateClientConVar("omniman_voicelines_enabled", 1, true, true, "Toggle voicelines", 0, 1)
CreateClientConVar("omniman_debris_enabled", 1, true, false, "Toggle debris", 0, 1)
CreateClientConVar("omniman_ldm_enabled", 0, true, false, "Low Detail Mode", 0, 1)
CreateClientConVar("omniman_debris_lifetime", 3, true, false, "Low Detail Mode", 0, 10000)

if CLIENT then
    concommand.Add("omniman_cleardebris", function( ply, cmd, args )
        for k, ent in ents.Iterator() do
            if ent.TableIndex and gebLib__DebrisList[ent.TableIndex] then
                gebLib_utils.RemoveDebris(ent)
                continue
            end
            if (ent:GetClass() == "geblib_decal") then
                ent:Remove()
            end
        end
        chat.AddText(Color(200, 0, 0), "[OMNI-MAN SWEP] ", color_white, "Debris removed")
    end)
end

----
----
----
hook.Add("PopulateToolMenu", "OmniMan.Spawnmenu.Settings", function()
    spawnmenu.AddToolMenuOption("Options", "Omni-Man SWEP", "OmniManSWEP_Config", language.GetPhrase("character.omni_man.settings"), "", "", function(panel)
        panel:ClearControls()

        panel:NumSlider(language.GetPhrase("character.omni_man.settings.superflight_sensitivity"), "omniman_cfg_superflight_sensitivity", 0, 1, 2)
        panel:ControlHelp(language.GetPhrase("character.omni_man.settings.superflight_sensitivity_hint"))
        panel:NumSlider(language.GetPhrase("character.omni_man.settings.damagemul"), "omniman_cfg_damagemul", 0, 10, 2)
        panel:ControlHelp(language.GetPhrase("character.omni_man.settings.damagemul_hint"))
        panel:NumSlider(language.GetPhrase("character.omni_man.settings.health"), "omniman_cfg_defaulthealth", 100, 100000, 0)
        panel:ControlHelp(language.GetPhrase("character.omni_man.settings.health_hint"))
        panel:NumSlider(language.GetPhrase("character.omni_man.settings.superarmor"), "omniman_cfg_superarmormul", 0.001, 10, 2)
        panel:ControlHelp(language.GetPhrase("character.omni_man.settings.superarmor_hint"))
        panel:CheckBox(language.GetPhrase("character.omni_man.settings.regenenabled"), "omniman_cfg_regenenabled", 0.001, 10, 2)
        panel:ControlHelp(language.GetPhrase("character.omni_man.settings.regenenabled_hint"))
    end)

    spawnmenu.AddToolMenuOption("Options", "Omni-Man SWEP", "OmniManSWEP_ConfigCL", language.GetPhrase("character.omni_man.settings_cl"), "", "", function(panel)
        panel:ClearControls()

        panel:CheckBox(language.GetPhrase("character.omni_man.settings_cl.toggledebris"), "omniman_debris_enabled")
        panel:ControlHelp(language.GetPhrase("character.omni_man.settings_cl.toggledebris_hint"))
        panel:CheckBox(language.GetPhrase("character.omni_man.settings_cl.ldm"), "omniman_ldm_enabled")
        panel:ControlHelp(language.GetPhrase("character.omni_man.settings_cl.ldm_hint"))
        panel:CheckBox(language.GetPhrase("character.omni_man.settings_cl.vo_enabled"), "omniman_voicelines_enabled")
        panel:ControlHelp(language.GetPhrase("character.omni_man.settings_cl.vo_enabled_hint"))
        panel:NumSlider(language.GetPhrase("character.omni_man.settings_cl.debrislifetime"), "omniman_debris_lifetime", 0.001, 100, 2)
        panel:ControlHelp(language.GetPhrase("character.omni_man.settings_cl.debrislifetime_hint"))
        panel:Button(language.GetPhrase("character.omni_man.settings_cl.cleardebris"), "omniman_cleardebris")
    end)
end)